# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

## <font color='red'> As respostas da avaliação devem ser inseridas no moodle </font>

In [ ]:
import numpy as np

### Exercício 1)
Considere o array `X` como descrito abaixo:
```python
[[0  1  2  3  4]
 [5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
```
Qual dos códigos abaixo retorna um array com os elementos 12, 18 e 6 a partir de `X`?

a) print(X[1,2,3])<br>
b) print(X[[2,3,1],[2,3,1]]) <br>
c) print(X[:,[2,3,1])<br>
d) print([1,2,3],:)

### Exercício 2)
Considerando o array `X` do exercício 1), qual dos códigos abaixo retorna o array 
```python
[[ 5  7  8]
 [10 12 13]]
```
a) print(X[1:3,0:2:3]])<br>
b) print(X[[1,2,3],[0,2,3]])<br>
c) print(X[1:3,:3])<br>
d) print(X[1:3,[0,2,3]])

### Exercício 3)
Considere o numpy array `A` abaixo:
```python
[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]
```
Qual das alternativas abaixo corresponde ao número de dimensões, a forma e ao número de elementos no array, respectivamente?

a) (5, 6) 2 2<br>
b) 2 (5, 6) 2<br>
c) (5, 6) 2 30<br>
d) 2 (5, 6) 30

In [7]:
import numpy as np
A =np.array([[ 2,19,16,1,12,7],[5,19,18,17,9,3],[16,4,18,11,4,2], [6,2,18,14,15,15], [4,8,1,14,19,13]])
print(A)


[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]


### Exercício 4) 
Considere o numpy array `A` do exercício anterior. Escreva um código para criar uma máscara para selecionar todos os elementos pares do array e armazena-los em um novo array unidimensional `B`. O resultado do comando
```python
print(B.size)
```
será:<br>
a) 13<br>
b) 15<br>
c) 16<br>
d) 17

In [8]:
#mask =  # escreva o código para criar a máscara

mask = (A%2==0)
B = np.flatten(A[mask])
print(B,B.size)
# copie e cole o resultado do print no moodle

[ 2 16 12 18 16  4 18  4  2  6  2 18 14  4  8 14] 16


### Exercício 5)
Ainda considerando o array `A` do exercício 3), que alternativa melhor explica o que o código abaixo está realizando:
```python
l_mask = [(i%2==0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```
a) insere elementos -1 nas colunas ímpares de `A` utilizando uma máscara booleana<br>
b) insere elementos -1 nas linhas pares e colunas ímpares de `A` utilizando uma máscara booleana<br>
c) insere elementos -1 nas linhas ímpares e colunas pares de `A` utilizando uma máscara booleana<br>
c) troca os elementos pares da matriz por -1 utilizando uma máscara booleana