# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte II e Matplotlib - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [9]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo corretamente utiliza broadcasting para construir uma matriz cujas **colunas** são todas formadas pelos elementos [0,1,2,3]?
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a)
```python
A[:] = v[:,np.newaxis]
```
b) 
```python
A[:] = v.reshape(4,1)
```
c)
```python
A[:] = v
A = A.T
```
d) Todas as alternativas estão corretas

In [13]:
A = np.zeros((4,4))
v = np.arange(4).reshape(4,1)
A[:] = v
print(A)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


### Exercício 2)
Qual das alternativas corretamente explica como o array `W` está sendo calculando no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

a) O array `W` possui 10 elementos como resultado da soma dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.<br>
c) O array `W` é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 linhas e o array `u` em 10 linhas.<br>
d) O array `W` possui 7 elementos como resultado da soma dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.

In [15]:
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
print(W.shape)

(10, 7)


### Exercício 3)
Considere a matriz abaixo. Utilizando redução, encontre o **índice da linha** que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha 6<br>
b) linha 0<br>
c) linha 8<br>
d) linha 9

In [17]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
print(f'The shape of A is {A.shape}')
print(f"The line with the largest sum of members is={np.argmax(A.sum(axis=1))}")

The shape of A is (10, 10)
[53 47 25 29 37 44 46 45 60 35]
The line with the largest sum of members is=8


### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o **índice da coluna** que possui a menor média de valores?

a) coluna 2<br>
b) coluna 0<br>
c) coluna 8<br>
d) coluna 9

In [18]:
column = np.argmin(A.mean(axis=0))
print(column)

2


### Exercício 5)
Suponha que a variável `A` no código abaixo é uma matriz com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
b) Substituindo o maior valor de cada linha por -1<br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [23]:
A = np.random.randint(low=0, high=10, size=25).reshape(5,5)
print(A)
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
print(A)

[[9 8 1 0 1]
 [7 3 9 9 0]
 [0 0 7 2 6]
 [6 3 1 0 4]
 [4 5 2 6 7]]
[[-1  8  1  0  1]
 [ 7  3  9 -1  0]
 [ 0  0 -1  2  6]
 [-1  3  1  0  4]
 [ 4  5  2  6 -1]]
